all:
  hosts:
    master:
      ansible_host: 10.1.10.5
      ip: 10.1.10.5
      access_ip: 10.1.10.5
    node:
      ansible_host: 10.1.10.6
      ip: 10.1.10.6
      access_ip: 10.1.10.6
  children:
    kube-master:
      hosts:
        master:
    kube-node:
      hosts:
        node:
    etcd:
      hosts:
        master:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
